FROM oven/bun:latest

WORKDIR /frontend

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json

COPY ./turbo.json ./turbo.json

COPY ./apps/frontend ./apps/frontend

RUN bun install


EXPOSE 3001

CMD [ "bun","run","start" ]
