FROM oven/bun:latest

WORKDIR /http

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./packages.json ./packages.json

COPY ./turbo.json ./turbo.json

COPY ./app/http-backend ./apps/http-backend

RUN bun install


EXPOSE 3000

CMD [ "bun","run","start" ]
